### PR TITLE
Update lock abstraction of defaultLogger.

### PR DESCRIPTION
**Pull request by cep21**
Just a first small change about how locks are referenced.  This moves
the lock from an extension like parameter of defaultLogger to a
private member

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by cep21** [comment]
It appears the master build of aws-xray-sdk-go is failing due to race conditions.  Those are independent of this diff.  We should look into resolving those, but maybe not at the same time as this change.

**Comment by luluzhao** [comment]
@cep21 thank you for submitting this PR. I think we have to fix the data race condition before accepting PRs since once the travis ci is broken, it will prevent others to merge the PR. What's more, by reading the error, it is the first time for us to see it. I think we have to fix the mutex in centralized sampling first.

**Comment by cep21** [comment]
These jenkins failures may be problems with jenkins.  Is it possible to retrigger the build? https://travis-ci.org/aws/aws-xray-sdk-go/jobs/539947195

**Comment by luluzhao** [comment]
@cep21 , I restart the build and from the log I saw it was test time out. Let's see how it goes this time.

**Pull request merged**
