### PR TITLE
feature: instrumentation for fasthttp

### PR DESCRIPTION
**Pull request by nicolascb**
Issue #133 

Instrumentation for [fasthttp](https://github.com/valyala/fasthttp).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by devdrops** [comment]
Come on @aws, you know what to do...

**Comment by awssandra** [comment]
Thanks for the contribution nicolascb! We will review shortly. Also, did you see the discussion over at: https://github.com/valyala/fasthttp/issues/940?

**Comment by nicolascb** [comment]
> Thanks for the contribution nicolascb! We will review shortly. Also, did you see the discussion over at: [valyala/fasthttp#940](https://github.com/valyala/fasthttp/issues/940)?

Yes @awssandra . This PR does not support fasthttp.Client, only trace incoming requests.

**Comment by bhautikpip** [comment]
Thanks for submitting this PR! I will take a look and post feedback.

**Comment by bhautikpip** [comment]
Hi @nicolascb ,

I would recommend you to submit only instrumentation related changes in this PR. I see that this PR also introduces couple of other good modifications (such as moving `httpTrace` method code). If we create separate PRs for instrumentation and other enhancements then it would be good for review.

**Comment by nicolascb** [comment]
Hi @bhautikpip,

Thanks for the feedback, I already opened a new PR with the changes in httpTrace: #296

**Pull request closed without merging**
