### PR TITLE
Fix vulnerability

### PR DESCRIPTION
**Pull request by AbhilashVijayakumar**
*Issue reported in our internal security scan - please refer screenshot and recommendation
Screenshot 2022-09-14 at 12 02 37 PM

*Description of changes:*
upgrade to aws-sdk-go@v1.44.97

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by atshaw43** [comment]
@AbhilashVijayakumar
The tests are failing. Can you please take a look?

**Comment by AbhilashVijayakumar** [comment]
> @AbhilashVijayakumar The tests are failing. Can you please take a look?

Updated unit test @atshaw43 commit https://github.com/aws/aws-xray-sdk-go/pull/378/commits/7f55dcee1cca4204110b02e56969883749d7f43b

**Comment by AbhilashVijayakumar** [comment]
@atshaw43 all tests are passing in https://github.com/SPHTech/aws-xray-sdk-go is the github actions in this repo pulling the incorrect repo to test against can help to review
Screenshot 2022-10-18 at 5 22 06 PM
Screenshot 2022-10-18 at 5 27 01 PM

**Comment by atshaw43** [comment]
I pulled down the code locally and tested it and it ran fine. Can you kick off the tests again? I don't seem to have permission to.

**Comment by atshaw43** [comment]
You might also try pulling the changes from this fork into yours and re-testing.

**Comment by atshaw43** [comment]
I fixed the tests in a side pull request and merged them since I could not edit this one.

This PR can be closed.

https://github.com/aws/aws-xray-sdk-go/pull/390

**Pull request closed without merging**
