### PR TITLE
Add xray.AWSv2() for aws-go-sdk-v2 compatibility

### PR DESCRIPTION
**Pull request by breml**
*Issue #, if available:*
Related to: #53

*Description of changes:*
Add `xray.AWSv2()` for compatibility with [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2).

This is maybe not the nicest implementation, because it includes a lot of code duplication from `aws.go`. The problem is, that the types `client.Client` (from [aws-sdk-go](https://github.com/aws/aws-sdk-go)) and `aws.Client` (from [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2)) can not be used interchangeably and a common interface, which would work with both is to my knowledge currently not present.

### CODE REVIEW

**Comment by danielpsf** [comment]
Hey guys, any news on this? REALLY in need of this!

**Comment by haotianw465** [comment]
Hi all, the `aws-sdk-go-v2` is still in developer preview and some X-Ray tracing related components are still subject to change. We will work with AWS Go SDK team to support a more stable version as early as possible. Please stay tuned and thank you for your patience.

**Comment by danielpsf** [comment]
In order to use Go Module I had to go to the V2, which means I've lost support for X-Ray, so I do appreciate your reply. ☺️

**Comment by cep21** [comment]
aws/aws-sdk-go is tagged as v1.19.41 and since it is pre-v1 release should work correctly with modules.

**Comment by breml** [comment]
Thanks dear stale-bot for the kind reminder. I clearly see no interest from the maintainers in this PR so I will close it.

**Pull request closed without merging**
